server:      #用户端口一般都是80，例如www.baidu.com不用加80
  port: 80   #可以通过HTTP地址（即常说的“网址”）加“: 80”来访问网站，因为浏览网页服务默认的端口号都是80，因此只需输入网址即可，不用输入“: 80”了。
spring:
  application:
    name: cloud-order-service  #eureka界面的application,被转换成了大写CLOUD-ORDER-SERVICE
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true #是否向注册中心注册自己，是否在eureka界面显示
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #      向defaultZone后的地址注册80端口
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    #将eureka界面的status名字从 cookie:cloud-order-service:80改为order80
    instance-id: order80
    prefer-ip-address: true  #给payment8001名字配上本机的ip地址，鼠标放名字左下角显示名字