server:
  port: 7001
eureka:
  instance:
    #可以用http://eureka7001.com:7001/访问7001端口的eureka界面
    #可以用http://localhost:7001/访问7001端口的eureka界面
    hostname: eureka7001.com #eureka服务端的实例名称，
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #7001和7002eurake的相互关联
      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    在服务类搭配lease-renewal-interval-in-seconds等使用
#    #关闭自我保护机制，保证不可用服务被及时剔除
#    eureka界面显示：THE SELF PRESERVATION MODE IS TURNED OFF. THIS MAY NOT PROTECT INSTANCE EXPIRY IN CASE OF NETWORK/OTHER PROBLEMS.
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000


